import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import MobileNav from "./components/mobile-nav";
import { Toaster } from "sonner";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin", "latin-ext"],
  weight: ["500", "300"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins} antialiased`}
      >
        <Toaster />
        <div className="w-full">
          <Nav />
          <MobileNav />
        </div>
        <div className="h-full min-h-[100vh]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
