const workers = [
  {
    id: "1",
    image: "/images/Randy.jpg",
    names: "Ngai Randy",
    role: "CEO",
    department: "Software Engineering",
    school: "CITEC Higher Institute of Technology and Management",
    skills: [
      "Software Developer",
      "Problem-Solving",
      "Communication",
      "Teamwork",
      "Adaptability",
    ],
    hobbies: [
      "Technology",
      "Traveling",
      "Skit making",
      "Classical music",
      "Gaming",
    ],
  },
  {
    id: "2",
    image: "/images/zenah.jpg",
    names: "ZENAH NEH",
    role: "CEO",
    department: "Logistics and Transport Management",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Communication", "Management", "Adaptability"],
    hobbies: ["Cooking", "Music", "Reading"],
  },
  {
    id: "3",
    image: "/images/suzane.jpg",
    names: "Likove Namondo Sussan",
    role: "CEO",
    department: "Accountancy",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Communication", "Listening", "Collaboration", "Adaptability"],
    hobbies: ["Gardening", "Music", "Reading"],
  },
  {
    id: "4",
    image: "/images/yasmine.jpg",
    names: "NTCHIA YASMIN NINKO CHISEMDY",
    role: "CEO",
    department: "Logistics and Transport Management",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Communication", "Teamwork", "Adaptability"],
    hobbies: ["Traveling", "Music", "Content Creating"],
  },
  {
    id: "5",
    image: "/images/tabot.jpg",
    names: "TABOT EMMANUEL MBI ANYANG",
    role: "CEO",
    department: "Accountancy",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Listening", "Teamwork", "Time Management"],
    hobbies: ["Basketball", "Gaming", "Reading"],
  },
  {
    id: "6",
    image: "/images/edelle.jpg",
    names: "LUKONG EDELL DZENYUY",
    role: "CEO",
    department: "Human Resource Management",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Listening", "Communication", "Adaptability"],
    hobbies: ["Singing", "Music", "Traveling"],
  },
  {
    id: "7",
    image: "/images/hannah.jpg",
    names: "MBI HANNAH NJEI",
    role: "CEO",
    department: "BANKING and FINANCE",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Teamwork", "Communication", "Adaptability"],
    hobbies: ["Singing", "Dancing", "Cooking"],
  },
  {
    id: "8",
    image: "/images/raul.jpg",
    names: "SHIYNTENG NENGHA RAUL",
    role: "CEO",
    department: "BANKING and FINANCE",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Communication"],
    hobbies: ["Sports", "Music"],
  },
  {
    id: "9",
    image: "/images/stephane.jpg",
    names: "Forlemu N. Guy Stephane",
    role: "CEO",
    department: "Software Engineering",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Software Developer", "Communication", "Adaptability", "Teamwork"],
    hobbies: ["Music", "Gaming", "Movie", "Anime"],
  },
  {
    id: "10",
    image: "/images/ngala.jpg",
    names: "NGALA NFONJI R. R.",
    role: "CEO",
    department: "Project Management",
    school: "CITEC Higher Institute of Technology and Management",
    skills: [
      "Digital Marketing",
      "MS Office",
      "Project Software",
      "Leadership",
      "Teamwork",
      "Language Proficiency",
    ],
    hobbies: ["Writing", "Video and Music Production", "Hiking", "Photography"],
  },
  {
    id: "11",
    image: "/images/mbah.jpg",
    names: "Zaolefack Emmanuel Zatah.",
    role: "CEO",
    department: "Project Management",
    school: "CITEC Higher Institute of Technology and Management",
    skills: ["Buying and Selling"],
    hobbies: ["Sport", "Dancing", "Swimming"],
  },
];

export default workers;
